### ISSUE TITLE
Create reversed cherry mx library

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/ugl-kicad-lib#6]
Per this comment https://github.com/UltimateHackingKeyboard/electronics/issues/14#issuecomment-171473013

Make the following parts
- [x] cherry mx (pcb) + matias reversed
- [x] cherry mx (pcb) + matias + leds reversed

**Comment by mondalaci** [comment]
How does the reversed switch differ from its non-reversed counterpart? I think it doesn't. We can simply rotate the existing switch module on the board by 180 degrees.

**Comment by spuder** [comment]
yes, this footprint doesn't differ from the merge request I opened earlier. The only difference is I added a second footprint with led holes. 

If you look close, you will notice that the pads on the left is #2, and the right is #1 
If we rotate the switch on the board 180 degrees, it will actually simplify the layout if we put pin #1 on the left.
